"""Public package surface for clearmetric-core."""

from __future__ import annotations

from ._version import __version__
from .aliases import load_table_alias_map
from .errors import (
    AdapterError,
    AliasMapError,
    CanonicalIdError,
    ClearMetricError,
    CompilerError,
    EmitterError,
    MergeConflictError,
    PolicyError,
    ProjectConfigError,
    SecurityFloorError,
    StructuralCheckError,
    ValidationError,
)
from .ids import (
    asset_id,
    column_id,
    cte_id,
    leaf_name,
    measure_id,
    model_id,
    normalize_identifier,
    normalize_identifier_part,
    normalize_identifier_parts,
    page_id,
    parse_column_selection,
    report_id,
    schema_name,
    split_qualified_identifier,
    table_id,
    visual_id,
)
from .interop import (
    AliasMap,
    apply_alias_map,
    attach_warehouse_bindings,
    normalize_fqn_for_matching,
    resolve_table_match,
    warehouse_table_fqn_candidates,
    warehouse_table_fqn_candidates_from_name,
)
from .merge import merge
from .models import (
    CatalogArtifact,
    DerivationState,
    Edge,
    Evidence,
    MatchStatus,
    Node,
    PhysicalBinding,
    Warning,
)
from .project import ClearMetricProject, load_project_aliases, load_project_config
from .serialize import render_json
from .validate import load_artifact_file, validate_artifact_dict, validate_project_dict

__all__ = [
    "__version__",
    "AdapterError",
    "AliasMap",
    "AliasMapError",
    "CatalogArtifact",
    "ClearMetricProject",
    "ClearMetricError",
    "CanonicalIdError",
    "CompilerError",
    "DerivationState",
    "EmitterError",
    "MatchStatus",
    "MergeConflictError",
    "Node",
    "PhysicalBinding",
    "PolicyError",
    "ProjectConfigError",
    "SecurityFloorError",
    "StructuralCheckError",
    "ValidationError",
    "apply_alias_map",
    "attach_warehouse_bindings",
    "asset_id",
    "column_id",
    "cte_id",
    "Edge",
    "Evidence",
    "leaf_name",
    "load_artifact_file",
    "load_project_aliases",
    "load_project_config",
    "load_table_alias_map",
    "measure_id",
    "merge",
    "model_id",
    "normalize_fqn_for_matching",
    "normalize_identifier",
    "normalize_identifier_part",
    "normalize_identifier_parts",
    "page_id",
    "parse_column_selection",
    "render_json",
    "report_id",
    "resolve_table_match",
    "schema_name",
    "split_qualified_identifier",
    "table_id",
    "validate_artifact_dict",
    "validate_project_dict",
    "visual_id",
    "warehouse_table_fqn_candidates",
    "warehouse_table_fqn_candidates_from_name",
    "Warning",
]
