#!/usr/bin/env python3
"""Generate docs/reference/cli.md from clearmetric.cli.build_parser()."""

from __future__ import annotations

import argparse
import filecmp
import os
import tempfile
from collections.abc import Iterator
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "docs" / "reference" / "cli.md"
BANNER = "<!-- AUTO-GENERATED by scripts/generate_wiki.py — do not edit -->\n\n"


def _walk_parser(
    parser: argparse.ArgumentParser,
    prefix: tuple[str, ...] = (),
) -> Iterator[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    yield prefix, parser
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, subparser in action.choices.items():
            yield from _walk_parser(subparser, prefix + (name,))


def _command_paths(parser: argparse.ArgumentParser) -> set[tuple[str, ...]]:
    return {prefix for prefix, _ in _walk_parser(parser) if prefix}


def _parser_for_experimental(enabled: bool) -> argparse.ArgumentParser:
    if enabled:
        os.environ["CM_EXPERIMENTAL"] = "1"
    else:
        os.environ.pop("CM_EXPERIMENTAL", None)
    from clearmetric.cli import build_parser

    return build_parser()


def _format_command(prefix: tuple[str, ...]) -> str:
    if not prefix:
        return "cm"
    return "cm " + " ".join(prefix)


def _render_help_block(parser: argparse.ArgumentParser) -> str:
    return f"```text\n{parser.format_help()}```\n"


def render_cli_reference() -> str:
    public_parser = _parser_for_experimental(False)
    public_paths = _command_paths(public_parser)
    if not public_paths:
        raise RuntimeError("build_parser() returned no subcommands")

    experimental_parser = _parser_for_experimental(True)
    experimental_paths = _command_paths(experimental_parser) - public_paths

    lines = [
        BANNER,
        "# CLI reference\n",
        "Generated from `clearmetric.cli.build_parser()`.\n",
        "## Root\n",
        f"### `{_format_command(())}`\n",
        _render_help_block(public_parser),
        "## Public commands\n",
    ]

    for prefix in sorted(public_paths):
        subparser = next(
            parser for path, parser in _walk_parser(public_parser) if path == prefix
        )
        lines.append(f"### `{_format_command(prefix)}`\n")
        lines.append(_render_help_block(subparser))

    if experimental_paths:
        lines.append("## Experimental commands\n")
        lines.append(
            "Requires `CM_EXPERIMENTAL=1`. Local debug only — not an auth server.\n"
        )
        for prefix in sorted(experimental_paths):
            subparser = next(
                parser
                for path, parser in _walk_parser(experimental_parser)
                if path == prefix
            )
            lines.append(f"### `{_format_command(prefix)}`\n")
            lines.append(_render_help_block(subparser))

    return "".join(lines)


def write_cli_reference() -> Path:
    content = render_cli_reference()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    return OUTPUT


def check_cli_reference() -> None:
    if not OUTPUT.is_file():
        raise SystemExit(
            f"generate_wiki: missing {OUTPUT.relative_to(REPO)} — run without --check"
        )
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as handle:
        handle.write(render_cli_reference())
        temp_path = Path(handle.name)
    try:
        if filecmp.cmp(temp_path, OUTPUT, shallow=False):
            return
        raise SystemExit(
            "generate_wiki: docs/reference/cli.md is stale — run: python scripts/generate_wiki.py"
        )
    finally:
        temp_path.unlink(missing_ok=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate dev wiki CLI reference")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs/reference/cli.md is stale",
    )
    args = parser.parse_args(argv)
    if args.check:
        check_cli_reference()
        print("generate_wiki: docs/reference/cli.md is up to date")
        return 0
    path = write_cli_reference()
    print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
